openapi: 3.0.3
info:
  title: CS453 Semeter Project API
  version: 1.0.0
  description: First Swagger doc, describing basic CRUD operations on a list of tasks

security:
  - bearerAuth: []

servers:
  - url: http://localhost:3000

paths:
  /auth/login:
    post:
      security: []
      summary: "Login"
      requestBody:
        description: "needs a username and password"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsernameAndPassword"
      responses:
        "201":
          description: "Null response"
        "400":
          description: "Invalid request, task not created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInvalidBody"

  /auth/me:
    get:
      summary: test login auth token
      responses:
        "200":
          description: Single user returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Username"
        "404":
          description: "Resource requested not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorNotFound"

  /users:
    get:
      summary: Get list of users
      responses:
        "200":
          description: List of users returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      summary: "Adds new user to list"
      security: []
      requestBody:
        description: "needs a username"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "201":
          description: "Null response"
        "400":
          description: "Invalid request, task not created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInvalidBody"

  /users/{name}:
    get:
      summary: Get user from list
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the user to get
      responses:
        "200":
          description: Single user returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: "Resource requested not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorNotFound"
    patch:
      summary: Update one user in list
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the user to update
      requestBody:
        description: "Users are allowed to replace their own password. Admins may replace the password and role of any user"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPatch"
      responses:
        "200":
          description: Single user returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: "Resource requested not found and could not be altered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorNotFound"
        "400":
          description: "Invalid request, User not updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInvalidBody"
    delete:
      summary: Delete User from db
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the User to delete
      responses:
        "204":
          description: "Null response"
        "404":
          description: "Resource requested not found and therefore not deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorNotFound"

  #
  # Remember:
  # - Express routes use :id, such as /tasks/:id.
  # - OpenAPI paths use {id}, such as /tasks/{id}.
  #
  # You may define schemas under components/schemas if you want to avoid
  # repeating the same object structure many times.

components:
  schemas:
    User:
      type: object
      required:
        - name
        - unhashed_pw
        - created_at
        - updated_at
      properties:
        name:
          type: string
          example: "exampleuser"
        unhashed_pw:
          type: string
          example: "some-unhashed-password-here"
        created_at:
          type: string
          example: "creation_time"
        updated_at:
          type: string
          example: "updated_time"
    UserInput:
      type: object
      required:
        - name
        - unhashed_pw
      properties:
        name:
          type: string
          example: "exampleuser"
        unhashed_pw:
          type: string
          example: "some-unhashed-password-here"
    UserPatch:
      type: object
      properties:
        unhashed_pw:
          type: string
          example: "some-unhashed-password-here"
        role:
          type: string
          example: "user"
  # DONE: Define an ErrorResponse schema with an error message.
    ErrorNotFound:
      type: object
      properties:
        Error:
          type: string
          example: "The resource you were looking for could not be found, please correct your path and try again"
    ErrorInvalidBody:
      type: object
      properties:
        Error:
          type: string
          example: "Invalid request body, please adjust your request and try again."
    UsernameAndPassword:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "user1@email.com"
        password:
          type: string
          example: "user1@email.com-password"
    Username:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          example: "exampleuser@email.com"
  securitySchemes:
    bearerAuth:            # Arbitrary name for the scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # Optional hint for documentation